# Generated by Django 5.2.17 on 2026-10-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_view_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='header_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first in the header (left to right).'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_header',
            field=models.BooleanField(default=False, help_text='Show this category in the site header navigation.'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['show_in_header', 'header_order'], name='catalog_cat_show_in_8cb992_idx'),
        ),
    ]
